from typing import Dict, NamedTuple, Optional

from BaseClasses import Location
from .Regions import RegionNames, NPCRegions

class ScarletMaidenLocation(Location):
    game: str = "Scarlet Maiden"


class ScarletMaidenLocationData(NamedTuple):
    category: str
    code: Optional[int]
    regions: Optional[list[str]] = None


def get_locations_by_category(category: str) -> Dict[str, ScarletMaidenLocationData]:
    location_dict: Dict[str, ScarletMaidenLocationData] = {}
    for name, data in location_table.items():
        if data.category == category:
            location_dict.setdefault(name, data)

    return location_dict

location_table: Dict[str, ScarletMaidenLocationData] = {
    # Skill Tree (Non-Progressive)
    "Vitality":                     ScarletMaidenLocation("Skill Tree", 1_0_2_00),
    "Wizardry":                     ScarletMaidenLocation("Skill Tree", 1_1_1_00),
    "Durability":                   ScarletMaidenLocation("Skill Tree", 1_1_2_00),
    "Aggression":                   ScarletMaidenLocation("Skill Tree", 1_1_3_00),
    "Arcane Economy":               ScarletMaidenLocation("Skill Tree", 1_2_0_00),
    "Magical Aptitude":             ScarletMaidenLocation("Skill Tree", 1_2_1_00),
    "Potion Mastery":               ScarletMaidenLocation("Skill Tree", 1_2_2_00),
    "Finesse":                      ScarletMaidenLocation("Skill Tree", 1_2_3_00),
    "Lethality":                    ScarletMaidenLocation("Skill Tree", 1_2_4_00),
    "Frozen Heart":                 ScarletMaidenLocation("Skill Tree", 1_3_0_00),
    "Elixir Of Life":               ScarletMaidenLocation("Skill Tree", 1_3_2_00),
    "Spear Mastery":                ScarletMaidenLocation("Skill Tree", 1_3_4_00),
    "Pyromancy":                    ScarletMaidenLocation("Skill Tree", 1_4_0_00),
    "Arcane Concentration":         ScarletMaidenLocation("Skill Tree", 1_4_1_00),
    "Sin Collector":                ScarletMaidenLocation("Skill Tree", 1_4_2_00),
    "Close Quarters Specialist":    ScarletMaidenLocation("Skill Tree", 1_4_3_00),
    "Dagger Mastery":               ScarletMaidenLocation("Skill Tree", 1_4_4_00),
    "Arcanist":                     ScarletMaidenLocation("Skill Tree", 1_5_0_00),
    "Elixir Of Mana":               ScarletMaidenLocation("Skill Tree", 1_5_2_00),
    "Hammer Mastery":               ScarletMaidenLocation("Skill Tree", 1_5_3_00),
    "Sword Mastery":                ScarletMaidenLocation("Skill Tree", 1_5_4_00),
    "Mana Surge":                   ScarletMaidenLocation("Skill Tree", 1_6_0_00),
    "Arcane Brilliance":            ScarletMaidenLocation("Skill Tree", 1_6_1_00),
    "Luck":                         ScarletMaidenLocation("Skill Tree", 1_6_2_00),
    "Vitality II":                  ScarletMaidenLocation("Skill Tree", 1_6_3_00),
    "Dash Mastery":                 ScarletMaidenLocation("Skill Tree", 1_6_4_00),
    "Wizardry II":                  ScarletMaidenLocation("Skill Tree", 1_7_0_00),
    "Potion Mastery II":            ScarletMaidenLocation("Skill Tree", 1_7_2_00),
    "Aggression II":                ScarletMaidenLocation("Skill Tree", 1_7_4_00),
    "Arcane Concentration II":      ScarletMaidenLocation("Skill Tree", 1_8_0_00),
    "Vitality III":                 ScarletMaidenLocation("Skill Tree", 1_8_2_00),
    "Finesse II":                   ScarletMaidenLocation("Skill Tree", 1_8_4_00),
    "Wizardry III":                 ScarletMaidenLocation("Skill Tree", 1_9_0_00),
    "Aggression III":               ScarletMaidenLocation("Skill Tree", 1_9_4_00),

    # Skill Tree (Progressive)
    **{f"Vitality Level {i}":                   ScarletMaidenLocation("Progressive Skill Tree", 1_0_2_00 + i) for i in range(1, 15)},
    **{f"Wizardry Level {i}":                   ScarletMaidenLocation("Progressive Skill Tree", 1_1_1_00 + i) for i in range(1, 5)},
    **{f"Durability Level {i}":                 ScarletMaidenLocation("Progressive Skill Tree", 1_1_2_00 + i) for i in range(1, 10)},
    **{f"Aggression Level {i}":                 ScarletMaidenLocation("Progressive Skill Tree", 1_1_3_00 + i) for i in range(1, 5)},
    **{f"Arcane Economy Level {i}":             ScarletMaidenLocation("Progressive Skill Tree", 1_2_0_00 + i) for i in range(1, 10)},
    **{f"Magical Aptitude Level {i}":           ScarletMaidenLocation("Progressive Skill Tree", 1_2_1_00 + i) for i in range(1, 10)},
    **{f"Potion Mastery Level {i}":             ScarletMaidenLocation("Progressive Skill Tree", 1_2_2_00 + i) for i in range(1, 1)},
    **{f"Finesse Level {i}":                    ScarletMaidenLocation("Progressive Skill Tree", 1_2_3_00 + i) for i in range(1, 10)},
    **{f"Lethality Level {i}":                  ScarletMaidenLocation("Progressive Skill Tree", 1_2_4_00 + i) for i in range(1, 10)},
    **{f"Frozen Heart Level {i}":               ScarletMaidenLocation("Progressive Skill Tree", 1_3_0_00 + i) for i in range(1, 5)},
    **{f"Elixir Of Life Level {i}":             ScarletMaidenLocation("Progressive Skill Tree", 1_3_2_00 + i) for i in range(1, 10)},
    **{f"Spear Mastery Level {i}":              ScarletMaidenLocation("Progressive Skill Tree", 1_3_4_00 + i) for i in range(1, 5)},
    **{f"Pyromancy Level {i}":                  ScarletMaidenLocation("Progressive Skill Tree", 1_4_0_00 + i) for i in range(1, 5)},
    **{f"Arcane Concentration Level {i}":       ScarletMaidenLocation("Progressive Skill Tree", 1_4_1_00 + i) for i in range(1, 5)},
    **{f"Sin Collector Level {i}":              ScarletMaidenLocation("Progressive Skill Tree", 1_4_2_00 + i) for i in range(1, 5)},
    **{f"Close Quarters Specialist Level {i}":  ScarletMaidenLocation("Progressive Skill Tree", 1_4_3_00 + i) for i in range(1, 5)},
    **{f"Dagger Mastery Level {i}":             ScarletMaidenLocation("Progressive Skill Tree", 1_4_4_00 + i) for i in range(1, 5)},
    **{f"Arcanist Level {i}":                   ScarletMaidenLocation("Progressive Skill Tree", 1_5_0_00 + i) for i in range(1, 5)},
    **{f"Elixir Of Mana Level {i}":             ScarletMaidenLocation("Progressive Skill Tree", 1_5_2_00 + i) for i in range(1, 10)},
    **{f"Hammer Mastery Level {i}":             ScarletMaidenLocation("Progressive Skill Tree", 1_5_3_00 + i) for i in range(1, 5)},
    **{f"Sword Mastery Level {i}":              ScarletMaidenLocation("Progressive Skill Tree", 1_5_4_00 + i) for i in range(1, 5)},
    **{f"Mana Surge Level {i}":                 ScarletMaidenLocation("Progressive Skill Tree", 1_6_0_00 + i) for i in range(1, 5)},
    **{f"Arcane Brilliance Level {i}":          ScarletMaidenLocation("Progressive Skill Tree", 1_6_1_00 + i) for i in range(1, 5)},
    **{f"Luck Level {i}":                       ScarletMaidenLocation("Progressive Skill Tree", 1_6_2_00 + i) for i in range(1, 10)},
    **{f"Vitality II Level {i}":                ScarletMaidenLocation("Progressive Skill Tree", 1_6_3_00 + i) for i in range(1, 5)},
    **{f"Dash Mastery Level {i}":               ScarletMaidenLocation("Progressive Skill Tree", 1_6_4_00 + i) for i in range(1, 10)},
    **{f"Wizardry II Level {i}":                ScarletMaidenLocation("Progressive Skill Tree", 1_7_0_00 + i) for i in range(1, 5)},
    **{f"Potion Mastery II Level {i}":          ScarletMaidenLocation("Progressive Skill Tree", 1_7_2_00 + i) for i in range(1, 2)},
    **{f"Aggression II Level {i}":              ScarletMaidenLocation("Progressive Skill Tree", 1_7_4_00 + i) for i in range(1, 5)},
    **{f"Arcane Concentration II Level {i}":    ScarletMaidenLocation("Progressive Skill Tree", 1_8_0_00 + i) for i in range(1, 5)},
    **{f"Vitality III Level {i}":               ScarletMaidenLocation("Progressive Skill Tree", 1_8_2_00 + i) for i in range(1, 10)},
    **{f"Finesse II Level {i}":                 ScarletMaidenLocation("Progressive Skill Tree", 1_8_4_00 + i) for i in range(1, 5)},
    **{f"Wizardry III Level {i}":               ScarletMaidenLocation("Progressive Skill Tree", 1_9_0_00 + i) for i in range(1, 10)},
    **{f"Aggression III Level {i}":             ScarletMaidenLocation("Progressive Skill Tree", 1_9_4_00 + i) for i in range(1, 10)},

    # Skill Tree (Insanity)
    '''
    **{f"Skill Tree [0,0] Level {i}":   ScarletMaidenLocation("Skill Tree Insanity", 1_0_0_00 + i) for i in range(1, 100)},
    **{f"Skill Tree [0,1] Level {i}":   ScarletMaidenLocation("Skill Tree Insanity", 1_1_0_00 + i) for i in range(1, 100)},
    **{f"Skill Tree [0,2] Level {i}":   ScarletMaidenLocation("Skill Tree Insanity", 1_2_0_00 + i) for i in range(1, 100)},
    **{f"Skill Tree [0,3] Level {i}":   ScarletMaidenLocation("Skill Tree Insanity", 1_3_0_00 + i) for i in range(1, 100)},
    **{f"Skill Tree [0,4] Level {i}":   ScarletMaidenLocation("Skill Tree Insanity", 1_4_0_00 + i) for i in range(1, 100)},
    **{f"Skill Tree [0,5] Level {i}":   ScarletMaidenLocation("Skill Tree Insanity", 1_5_0_00 + i) for i in range(1, 100)},
    **{f"Skill Tree [0,6] Level {i}":   ScarletMaidenLocation("Skill Tree Insanity", 1_6_0_00 + i) for i in range(1, 100)},
    **{f"Skill Tree [0,7] Level {i}":   ScarletMaidenLocation("Skill Tree Insanity", 1_7_0_00 + i) for i in range(1, 100)},
    **{f"Skill Tree [0,8] Level {i}":   ScarletMaidenLocation("Skill Tree Insanity", 1_8_0_00 + i) for i in range(1, 100)},
    **{f"Skill Tree [0,9] Level {i}":   ScarletMaidenLocation("Skill Tree Insanity", 1_9_0_00 + i) for i in range(1, 100)},
    **{f"Skill Tree [1,0] Level {i}":   ScarletMaidenLocation("Skill Tree Insanity", 1_0_1_00 + i) for i in range(1, 100)},
    **{f"Skill Tree [1,1] Level {i}":   ScarletMaidenLocation("Skill Tree Insanity", 1_1_1_00 + i) for i in range(1, 100)},
    **{f"Skill Tree [1,2] Level {i}":   ScarletMaidenLocation("Skill Tree Insanity", 1_2_1_00 + i) for i in range(1, 100)},
    **{f"Skill Tree [1,3] Level {i}":   ScarletMaidenLocation("Skill Tree Insanity", 1_3_1_00 + i) for i in range(1, 100)},
    **{f"Skill Tree [1,4] Level {i}":   ScarletMaidenLocation("Skill Tree Insanity", 1_4_1_00 + i) for i in range(1, 100)},
    **{f"Skill Tree [1,5] Level {i}":   ScarletMaidenLocation("Skill Tree Insanity", 1_5_1_00 + i) for i in range(1, 100)},
    **{f"Skill Tree [1,6] Level {i}":   ScarletMaidenLocation("Skill Tree Insanity", 1_6_1_00 + i) for i in range(1, 100)},
    **{f"Skill Tree [1,7] Level {i}":   ScarletMaidenLocation("Skill Tree Insanity", 1_7_1_00 + i) for i in range(1, 100)},
    **{f"Skill Tree [1,8] Level {i}":   ScarletMaidenLocation("Skill Tree Insanity", 1_8_1_00 + i) for i in range(1, 100)},
    **{f"Skill Tree [1,9] Level {i}":   ScarletMaidenLocation("Skill Tree Insanity", 1_9_1_00 + i) for i in range(1, 100)},
    **{f"Skill Tree [2,0] Level {i}":   ScarletMaidenLocation("Skill Tree Insanity", 1_0_2_00 + i) for i in range(1, 100)},
    **{f"Skill Tree [2,1] Level {i}":   ScarletMaidenLocation("Skill Tree Insanity", 1_1_2_00 + i) for i in range(1, 100)},
    **{f"Skill Tree [2,2] Level {i}":   ScarletMaidenLocation("Skill Tree Insanity", 1_2_2_00 + i) for i in range(1, 100)},
    **{f"Skill Tree [2,3] Level {i}":   ScarletMaidenLocation("Skill Tree Insanity", 1_3_2_00 + i) for i in range(1, 100)},
    **{f"Skill Tree [2,4] Level {i}":   ScarletMaidenLocation("Skill Tree Insanity", 1_4_2_00 + i) for i in range(1, 100)},
    **{f"Skill Tree [2,5] Level {i}":   ScarletMaidenLocation("Skill Tree Insanity", 1_5_2_00 + i) for i in range(1, 100)},
    **{f"Skill Tree [2,6] Level {i}":   ScarletMaidenLocation("Skill Tree Insanity", 1_6_2_00 + i) for i in range(1, 100)},
    **{f"Skill Tree [2,7] Level {i}":   ScarletMaidenLocation("Skill Tree Insanity", 1_7_2_00 + i) for i in range(1, 100)},
    **{f"Skill Tree [2,8] Level {i}":   ScarletMaidenLocation("Skill Tree Insanity", 1_8_2_00 + i) for i in range(1, 100)},
    **{f"Skill Tree [2,9] Level {i}":   ScarletMaidenLocation("Skill Tree Insanity", 1_9_2_00 + i) for i in range(1, 100)},
    **{f"Skill Tree [3,0] Level {i}":   ScarletMaidenLocation("Skill Tree Insanity", 1_0_3_00 + i) for i in range(1, 100)},
    **{f"Skill Tree [3,1] Level {i}":   ScarletMaidenLocation("Skill Tree Insanity", 1_1_3_00 + i) for i in range(1, 100)},
    **{f"Skill Tree [3,2] Level {i}":   ScarletMaidenLocation("Skill Tree Insanity", 1_2_3_00 + i) for i in range(1, 100)},
    **{f"Skill Tree [3,3] Level {i}":   ScarletMaidenLocation("Skill Tree Insanity", 1_3_3_00 + i) for i in range(1, 100)},
    **{f"Skill Tree [3,4] Level {i}":   ScarletMaidenLocation("Skill Tree Insanity", 1_4_3_00 + i) for i in range(1, 100)},
    **{f"Skill Tree [3,5] Level {i}":   ScarletMaidenLocation("Skill Tree Insanity", 1_5_3_00 + i) for i in range(1, 100)},
    **{f"Skill Tree [3,6] Level {i}":   ScarletMaidenLocation("Skill Tree Insanity", 1_6_3_00 + i) for i in range(1, 100)},
    **{f"Skill Tree [3,7] Level {i}":   ScarletMaidenLocation("Skill Tree Insanity", 1_7_3_00 + i) for i in range(1, 100)},
    **{f"Skill Tree [3,8] Level {i}":   ScarletMaidenLocation("Skill Tree Insanity", 1_8_3_00 + i) for i in range(1, 100)},
    **{f"Skill Tree [3,9] Level {i}":   ScarletMaidenLocation("Skill Tree Insanity", 1_9_3_00 + i) for i in range(1, 100)},
    **{f"Skill Tree [4,0] Level {i}":   ScarletMaidenLocation("Skill Tree Insanity", 1_0_4_00 + i) for i in range(1, 100)},
    **{f"Skill Tree [4,1] Level {i}":   ScarletMaidenLocation("Skill Tree Insanity", 1_1_4_00 + i) for i in range(1, 100)},
    **{f"Skill Tree [4,2] Level {i}":   ScarletMaidenLocation("Skill Tree Insanity", 1_2_4_00 + i) for i in range(1, 100)},
    **{f"Skill Tree [4,3] Level {i}":   ScarletMaidenLocation("Skill Tree Insanity", 1_3_4_00 + i) for i in range(1, 100)},
    **{f"Skill Tree [4,4] Level {i}":   ScarletMaidenLocation("Skill Tree Insanity", 1_4_4_00 + i) for i in range(1, 100)},
    **{f"Skill Tree [4,5] Level {i}":   ScarletMaidenLocation("Skill Tree Insanity", 1_5_4_00 + i) for i in range(1, 100)},
    **{f"Skill Tree [4,6] Level {i}":   ScarletMaidenLocation("Skill Tree Insanity", 1_6_4_00 + i) for i in range(1, 100)},
    **{f"Skill Tree [4,7] Level {i}":   ScarletMaidenLocation("Skill Tree Insanity", 1_7_4_00 + i) for i in range(1, 100)},
    **{f"Skill Tree [4,8] Level {i}":   ScarletMaidenLocation("Skill Tree Insanity", 1_8_4_00 + i) for i in range(1, 100)},
    **{f"Skill Tree [4,9] Level {i}":   ScarletMaidenLocation("Skill Tree Insanity", 1_9_4_00 + i) for i in range(1, 100)},
    '''

    # Blacksmith
    "Rescue Bruce":                     ScarletMaidenLocationData("Bruce", 100_0000),
    **{f"Bruce Level {i}":              ScarletMaidenLocationData("Bruce Level", 100_0000 + i) for i in range(1, 26)},

    # Roman
    "Rescue Roman":                     ScarletMaidenLocationData("Roman", 200_0000),
    **{f"Roman Level {i}":              ScarletMaidenLocationData("Roman Level", 200_0000 + i) for i in range(1, 26)},

    # Faelina
    "Rescue Faelina":                   ScarletMaidenLocationData("Faelina", 300_0000),
    **{f"Faelina Level {i}":            ScarletMaidenLocationData("Faelina Level", 300_0000 + i) for i in range(1, 26)},

    # Candy
    "Rescue Candy":                         ScarletMaidenLocationData("Candy", 400_0000),
    "Mines of Sorrow - Area Complete":      ScarletMaidenLocation("Candy Teleport", 400_0001),
    "The Royal Library - Area Complete":    ScarletMaidenLocation("Candy Teleport", 400_0002),
    "Subterranean Forest - Area Complete":  ScarletMaidenLocation("Candy Teleport", 400_0003),
    "Frozen Passage - Area Complete":       ScarletMaidenLocation("Extra Candy Teleport", 400_0004),
    "Twisted Sanctum - Area Complete":      ScarletMaidenLocation("Extra Candy Teleport", 400_0005),

    # Gallerysanity
    "Gallerysanity: Orc Warrior":               ScarletMaidenLocation("Gallery", 20_001_0, NPCRegions.OrcWarrior),
    "Gallerysanity: Goblin Shooter":            ScarletMaidenLocation("Gallery", 20_002_0, NPCRegions.GoblinShooter),
    "Gallerysanity: Plant Girl":                ScarletMaidenLocation("Gallery", 20_003_0, NPCRegions.PlantGirl),
    "Gallerysanity: Triboob Huntress":          ScarletMaidenLocation("Gallery", 20_004_0, NPCRegions.TriboobHuntress),
    "Gallerysanity: Wicked Witch":              ScarletMaidenLocation("Gallery", 20_005_0, NPCRegions.WickedWitch),
    "Gallerysanity: Aqua Slime":                ScarletMaidenLocation("Gallery", 20_006_0, NPCRegions.AquaSlime),
    "Gallerysanity: Dark Elf Assassin":         ScarletMaidenLocation("Gallery", 20_007_0, NPCRegions.DarkElfAssassin),
    "Gallerysanity: Ruby Slime":                ScarletMaidenLocation("Gallery", 20_008_0, NPCRegions.RubySlime),
    "Gallerysanity: Orc Axe Thrower (Green)":   ScarletMaidenLocation("Gallery", 20_009_0, NPCRegions.OrcAxeThrowerGreen),
    "Gallerysanity: Succubus":                  ScarletMaidenLocation("Gallery", 20_010_0, NPCRegions.Succubus),
    "Gallerysanity: Wolfina":                   ScarletMaidenLocation("Gallery", 20_011_0, NPCRegions.Wolfina),
    "Gallerysanity: Gimp":                      ScarletMaidenLocation("Gallery", 20_012_0, NPCRegions.Gimp),
    "Gallerysanity: Fairie":                    ScarletMaidenLocation("Gallery", 20_013_0, NPCRegions.Fairie),
    "Gallerysanity: Triboob Crusher":           ScarletMaidenLocation("Gallery", 20_014_0, NPCRegions.TriboobCrusher),
    "Gallerysanity: Dark Elf Goddess":          ScarletMaidenLocation("Gallery", 20_015_0, NPCRegions.DarkElfGoddess),
    "Gallerysanity: Emerald Slime":             ScarletMaidenLocation("Gallery", 20_016_0, NPCRegions.EmeraldSlime),
    "Gallerysanity: Ogress":                    ScarletMaidenLocation("Gallery", 20_017_0, NPCRegions.Ogress),
    "Gallerysanity: Poison Ivy":                ScarletMaidenLocation("Gallery", 20_018_0, NPCRegions.PoisonIvy),
    "Gallerysanity: Corrupted Witch":           ScarletMaidenLocation("Gallery", 20_019_0, NPCRegions.CorruptedWitch),
    "Gallerysanity: Goblin Bomber":             ScarletMaidenLocation("Gallery", 20_020_0, NPCRegions.GoblinBomber),
    "Gallerysanity: Triboob Dragonslayer":      ScarletMaidenLocation("Gallery", 20_021_0, NPCRegions.TriboobDragonslayer),
    "Gallerysanity: Mama Slime":                ScarletMaidenLocation("Gallery", 20_022_0, NPCRegions.MamaSlime),
    "Gallerysanity: Shield Maiden":             ScarletMaidenLocation("Gallery", 20_023_0, NPCRegions.ShieldMaiden),
    "Gallerysanity: Snake Girl":                ScarletMaidenLocation("Gallery", 20_024_0, NPCRegions.SnakeGirl),
    "Gallerysanity: Dark Succubus":             ScarletMaidenLocation("Gallery", 20_025_0, NPCRegions.DarkSuccubus),
    "Gallerysanity: Orcish Gimp":               ScarletMaidenLocation("Gallery", 20_026_0, NPCRegions.OrcishGimp),
    "Gallerysanity: Foxy":                      ScarletMaidenLocation("Gallery", 20_027_0, NPCRegions.Foxy),
    "Gallerysanity: Orc Axe Thrower (Pink)":    ScarletMaidenLocation("Gallery", 20_028_0, NPCRegions.OrcAxeThrowerPink),
    "Gallerysanity: Snake Huntress":            ScarletMaidenLocation("Gallery", 20_029_0, NPCRegions.SnakeHuntress),
    "Gallerysanity: Imp Girl":                  ScarletMaidenLocation("Gallery", 20_030_0, NPCRegions.ImpGirl),
    "Gallerysanity: Golden Slime":              ScarletMaidenLocation("Gallery", 20_031_0, NPCRegions.GoldenSlime),
    "Gallerysanity: Count Cockula":             ScarletMaidenLocation("Gallery", 20_032_0, NPCRegions.CountCockula),
    "Gallerysanity: Elven Fountain":            ScarletMaidenLocation("Gallery", 20_033_0, NPCRegions.ElvenFountain),
    "Gallerysanity: Mysterious Djinn":          ScarletMaidenLocation("Gallery", 20_034_0, NPCRegions.MysteriousDjinn),
    "Gallerysanity: Horny Ogre":                ScarletMaidenLocation("Gallery", 20_035_0, NPCRegions.HornyOgre),
    "Gallerysanity: Underworld Nurse":          ScarletMaidenLocation("Gallery", 20_036_0, NPCRegions.UnderworldNurse),
    "Gallerysanity: Lactating Goddess":         ScarletMaidenLocation("Gallery", 20_037_0, NPCRegions.LactatingGoddess),
    "Gallerysanity: Shy Elf":                   ScarletMaidenLocation("Gallery", 20_038_0, NPCRegions.ShyElf),
    "Gallerysanity: Lusty Giant":               ScarletMaidenLocation("Gallery", 20_039_0, NPCRegions.LustyGiant),
    "Gallerysanity: Handsome Adventurer":       ScarletMaidenLocation("Gallery", 20_040_0, NPCRegions.HandsomeAdventurer),
    "Gallerysanity: Hungry Gnome":              ScarletMaidenLocation("Gallery", 20_041_0, NPCRegions.HungryGnome),
    "Gallerysanity: Creepy Bush":               ScarletMaidenLocation("Gallery", 20_042_0, NPCRegions.CreepyBush),
    "Gallerysanity: Frozen Maiden":             ScarletMaidenLocation("Gallery", 20_043_0, NPCRegions.FrozenMaiden),
    "Gallerysanity: Frosty Traveler":           ScarletMaidenLocation("Gallery", 20_044_0, NPCRegions.FrostyTraveler),
    "Gallerysanity: Mimic":                     ScarletMaidenLocation("Gallery", 20_045_0, NPCRegions.Mimic),
    "Gallerysanity: Rigor Mortis":              ScarletMaidenLocation("Gallery", 20_046_0, NPCRegions.RigorMortis),
    "Gallerysanity: Goblin King":               ScarletMaidenLocation("Gallery", 20_047_0, NPCRegions.GoblinKing),
    "Gallerysanity: Monument of Strength":      ScarletMaidenLocation("Gallery", 20_048_0, NPCRegions.MonumentOfStrength),
    "Gallerysanity: Friendly Witch":            ScarletMaidenLocation("Gallery", 20_049_0, NPCRegions.FriendlyWitch),
    "Gallerysanity: Stoned Wizard":             ScarletMaidenLocation("Gallery", 20_050_0, NPCRegions.StonedWizard),
    "Gallerysanity: Magic Dragon":              ScarletMaidenLocation("Gallery", 20_051_0, NPCRegions.MagicDragon),
    "Gallerysanity: Muscle Goddess":            ScarletMaidenLocation("Gallery", 20_052_0, NPCRegions.MuscleGoddess),
    "Gallerysanity: Medicine Man":              ScarletMaidenLocation("Gallery", 20_053_0, NPCRegions.MedicineMan),
    "Gallerysanity: Marvin's Mana Pump":        ScarletMaidenLocation("Gallery", 20_054_0, NPCRegions.MarvinsManaPump),
    "Gallerysanity: Steamy Contraptions":       ScarletMaidenLocation("Gallery", 20_055_0),
    "Gallerysanity: Masquerade":                ScarletMaidenLocation("Gallery", 20_056_0),
    "Gallerysanity: Magic Flute":               ScarletMaidenLocation("Gallery", 20_057_0),
    "Gallerysanity: Green Delight":             ScarletMaidenLocation("Gallery", 20_058_0),
    "Gallerysanity: It's a Strap!":             ScarletMaidenLocation("Gallery", 20_059_0),
    "Gallerysanity: Gold Digger":               ScarletMaidenLocation("Gallery", 20_060_0),
    "Gallerysanity: Portal of Pleasure":        ScarletMaidenLocation("Gallery", 20_061_0),
    "Gallerysanity: Earth Mother":              ScarletMaidenLocation("Gallery", 20_062_0, [RegionNames.MinesBoss]),
    "Gallerysanity: The Grand Archivist":       ScarletMaidenLocation("Gallery", 20_063_0, [RegionNames.LibraryBoss]),
    "Gallerysanity: Queen Lily":                ScarletMaidenLocation("Gallery", 20_064_0, [RegionNames.ForestBoss]),
    "Gallerysanity: Cold Hearted Bitch":        ScarletMaidenLocation("Gallery", 20_065_0, [RegionNames.FrozenBoss]),
    "Gallerysanity: Corrupted Maiden":          ScarletMaidenLocation("Gallery - Postgame", 20_066_0, [RegionNames.SanctumBoss]),
    "Gallerysanity: Scarlet & Faelina":         ScarletMaidenLocation("Gallery - Postgame", 20_067_0, [RegionNames.SanctumBoss]),
    "Gallerysanity: Misty & Candy":             ScarletMaidenLocation("Gallery - Postgame", 20_068_0, [RegionNames.SanctumBoss]),
    "Gallerysanity: Roman & Tiger":             ScarletMaidenLocation("Gallery - Postgame", 20_069_0, [RegionNames.SanctumBoss]),

    # Fucksanity
    "Fucksanity: Orc Warrior":                  ScarletMaidenLocation("Fucksanity", 30_001_0, NPCRegions.OrcWarrior),
    "Fucksanity: Goblin Shooter":               ScarletMaidenLocation("Fucksanity", 30_002_0, NPCRegions.GoblinShooter),
    "Fucksanity: Plant Girl":                   ScarletMaidenLocation("Fucksanity", 30_003_0, NPCRegions.PlantGirl),
    "Fucksanity: Triboob Huntress":             ScarletMaidenLocation("Fucksanity", 30_004_0, NPCRegions.TriboobHuntress),
    "Fucksanity: Wicked Witch":                 ScarletMaidenLocation("Fucksanity", 30_005_0, NPCRegions.WickedWitch),
    "Fucksanity: Aqua Slime":                   ScarletMaidenLocation("Fucksanity", 30_006_0, NPCRegions.AquaSlime),
    "Fucksanity: Dark Elf Assassin":            ScarletMaidenLocation("Fucksanity", 30_007_0, NPCRegions.DarkElfAssassin),
    "Fucksanity: Ruby Slime":                   ScarletMaidenLocation("Fucksanity", 30_008_0, NPCRegions.RubySlime),
    "Fucksanity: Orc Axe Thrower (Green)":      ScarletMaidenLocation("Fucksanity", 30_009_0, NPCRegions.OrcAxeThrowerGreen),
    "Fucksanity: Succubus":                     ScarletMaidenLocation("Fucksanity", 30_010_0, NPCRegions.Succubus),
    "Fucksanity: Wolfina":                      ScarletMaidenLocation("Fucksanity", 30_011_0, NPCRegions.Wolfina),
    "Fucksanity: Gimp":                         ScarletMaidenLocation("Fucksanity", 30_012_0, NPCRegions.Gimp),
    "Fucksanity: Fairie":                       ScarletMaidenLocation("Fucksanity", 30_013_0, NPCRegions.Fairie),
    "Fucksanity: Triboob Crusher":              ScarletMaidenLocation("Fucksanity", 30_014_0, NPCRegions.TriboobCrusher),
    "Fucksanity: Dark Elf Goddess":             ScarletMaidenLocation("Fucksanity", 30_015_0, NPCRegions.DarkElfGoddess),
    "Fucksanity: Emerald Slime":                ScarletMaidenLocation("Fucksanity", 30_016_0, NPCRegions.EmeraldSlime),
    "Fucksanity: Ogress":                       ScarletMaidenLocation("Fucksanity", 30_017_0, NPCRegions.Ogress),
    "Fucksanity: Poison Ivy":                   ScarletMaidenLocation("Fucksanity", 30_018_0, NPCRegions.PoisonIvy),
    "Fucksanity: Corrupted Witch":              ScarletMaidenLocation("Fucksanity", 30_019_0, NPCRegions.CorruptedWitch),
    "Fucksanity: Goblin Bomber":                ScarletMaidenLocation("Fucksanity", 30_020_0, NPCRegions.GoblinBomber),
    "Fucksanity: Triboob Dragonslayer":         ScarletMaidenLocation("Fucksanity", 30_021_0, NPCRegions.TriboobDragonslayer),
    "Fucksanity: Mama Slime":                   ScarletMaidenLocation("Fucksanity", 30_022_0, NPCRegions.MamaSlime),
    "Fucksanity: Shield Maiden":                ScarletMaidenLocation("Fucksanity", 30_023_0, NPCRegions.ShieldMaiden),
    "Fucksanity: Snake Girl":                   ScarletMaidenLocation("Fucksanity", 30_024_0, NPCRegions.SnakeGirl),
    "Fucksanity: Dark Succubus":                ScarletMaidenLocation("Fucksanity", 30_025_0, NPCRegions.DarkSuccubus),
    "Fucksanity: Orcish Gimp":                  ScarletMaidenLocation("Fucksanity", 30_026_0, NPCRegions.OrcishGimp),
    "Fucksanity: Foxy":                         ScarletMaidenLocation("Fucksanity", 30_027_0, NPCRegions.Foxy),
    "Fucksanity: Orc Axe Thrower (Pink)":       ScarletMaidenLocation("Fucksanity", 30_028_0, NPCRegions.OrcAxeThrowerPink),
    "Fucksanity: Snake Huntress":               ScarletMaidenLocation("Fucksanity", 30_029_0, NPCRegions.SnakeHuntress),
    "Fucksanity: Imp Girl":                     ScarletMaidenLocation("Fucksanity", 30_030_0, NPCRegions.ImpGirl),
    "Fucksanity: Golden Slime":                 ScarletMaidenLocation("Fucksanity", 30_031_0, NPCRegions.GoldenSlime),
    "Fucksanity: Earth Mother":                 ScarletMaidenLocation("Fucksanity - Boss", 30_062_0, [RegionNames.MinesBoss]),
    "Fucksanity: The Grand Archivist":          ScarletMaidenLocation("Fucksanity - Boss", 30_063_0, [RegionNames.LibraryBoss]),
    "Fucksanity: Queen Lily":                   ScarletMaidenLocation("Fucksanity - Boss", 30_064_0, [RegionNames.ForestBoss]),
    "Fucksanity: Cold Hearted Bitch":           ScarletMaidenLocation("Fucksanity - Boss", 30_065_0, [RegionNames.FrozenBoss]),
    "Fucksanity: Corrupted Maiden":             ScarletMaidenLocation("Fucksanity - Postgame", 30_066_0, [RegionNames.SanctumBoss]),
    
    # Heartsanity/Pumpsanity
    **{f"Heartsanity: Orc Warrior {i}":             ScarletMaidenLocationData("Heartsanity", 30_001_0 + i, NPCRegions.OrcWarrior) for i in range(1, 4)},
    **{f"Heartsanity: Goblin Shooter {i}":          ScarletMaidenLocationData("Heartsanity", 30_002_0 + i, NPCRegions.GoblinShooter) for i in range(1, 4)},
    **{f"Heartsanity: Plant Girl {i}":              ScarletMaidenLocationData("Heartsanity", 30_003_0 + i, NPCRegions.PlantGirl) for i in range(1, 4)},
    **{f"Heartsanity: Triboob Huntress {i}":        ScarletMaidenLocationData("Heartsanity", 30_004_0 + i, NPCRegions.TriboobHuntress) for i in range(1, 4)},
    **{f"Heartsanity: Wicked Witch {i}":            ScarletMaidenLocationData("Heartsanity", 30_005_0 + i, NPCRegions.WickedWitch) for i in range(1, 4)},
    **{f"Heartsanity: Aqua Slime {i}":              ScarletMaidenLocationData("Heartsanity", 30_006_0 + i, NPCRegions.AquaSlime) for i in range(1, 4)},
    **{f"Heartsanity: Dark Elf Assassin {i}":       ScarletMaidenLocationData("Heartsanity", 30_007_0 + i, NPCRegions.DarkElfAssassin) for i in range(1, 4)},
    **{f"Heartsanity: Ruby Slime {i}":              ScarletMaidenLocationData("Heartsanity", 30_008_0 + i, NPCRegions.RubySlime) for i in range(1, 4)},
    **{f"Heartsanity: Orc Axe Thrower (Green) {i}": ScarletMaidenLocationData("Heartsanity", 30_009_0 + i, NPCRegions.OrcAxeThrowerGreen) for i in range(1, 4)},
    **{f"Heartsanity: Succubus {i}":                ScarletMaidenLocationData("Heartsanity", 30_010_0 + i, NPCRegions.Succubus) for i in range(1, 4)},
    **{f"Heartsanity: Wolfina {i}":                 ScarletMaidenLocationData("Heartsanity", 30_011_0 + i, NPCRegions.Wolfina) for i in range(1, 4)},
    **{f"Heartsanity: Gimp {i}":                    ScarletMaidenLocationData("Heartsanity", 30_012_0 + i, NPCRegions.Gimp) for i in range(1, 4)},
    **{f"Heartsanity: Fairie {i}":                  ScarletMaidenLocationData("Heartsanity", 30_013_0 + i, NPCRegions.Fairie) for i in range(1, 4)},
    **{f"Heartsanity: Triboob Crusher {i}":         ScarletMaidenLocationData("Heartsanity", 30_014_0 + i, NPCRegions.TriboobCrusher) for i in range(1, 4)},
    **{f"Heartsanity: Dark Elf Goddess {i}":        ScarletMaidenLocationData("Heartsanity", 30_015_0 + i, NPCRegions.DarkElfGoddess) for i in range(1, 4)},
    **{f"Heartsanity: Emerald Slime {i}":           ScarletMaidenLocationData("Heartsanity", 30_016_0 + i, NPCRegions.EmeraldSlime) for i in range(1, 4)},
    **{f"Heartsanity: Ogress {i}":                  ScarletMaidenLocationData("Heartsanity", 30_017_0 + i, NPCRegions.Ogress) for i in range(1, 4)},
    **{f"Heartsanity: Poison Ivy {i}":              ScarletMaidenLocationData("Heartsanity", 30_018_0 + i, NPCRegions.PoisonIvy) for i in range(1, 4)},
    **{f"Heartsanity: Corrupted Witch {i}":         ScarletMaidenLocationData("Heartsanity", 30_019_0 + i, NPCRegions.CorruptedWitch) for i in range(1, 4)},
    **{f"Heartsanity: Goblin Bomber {i}":           ScarletMaidenLocationData("Heartsanity", 30_020_0 + i, NPCRegions.GoblinBomber) for i in range(1, 4)},
    **{f"Heartsanity: Triboob Dragonslayer {i}":    ScarletMaidenLocationData("Heartsanity", 30_021_0 + i, NPCRegions.TriboobDragonslayer) for i in range(1, 4)},
    **{f"Heartsanity: Mama Slime {i}":              ScarletMaidenLocationData("Heartsanity", 30_022_0 + i, NPCRegions.MamaSlime) for i in range(1, 4)},
    **{f"Heartsanity: Shield Maiden {i}":           ScarletMaidenLocationData("Heartsanity", 30_023_0 + i, NPCRegions.ShieldMaiden) for i in range(1, 4)},
    **{f"Heartsanity: Snake Girl {i}":              ScarletMaidenLocationData("Heartsanity", 30_024_0 + i, NPCRegions.SnakeGirl) for i in range(1, 4)},
    **{f"Heartsanity: Dark Succubus {i}":           ScarletMaidenLocationData("Heartsanity", 30_025_0 + i, NPCRegions.DarkSuccubus) for i in range(1, 4)},
    **{f"Heartsanity: Orcish Gimp {i}":             ScarletMaidenLocationData("Heartsanity", 30_026_0 + i, NPCRegions.OrcishGimp) for i in range(1, 4)},
    **{f"Heartsanity: Foxy {i}":                    ScarletMaidenLocationData("Heartsanity", 30_027_0 + i, NPCRegions.Foxy) for i in range(1, 4)},
    **{f"Heartsanity: Orc Axe Thrower (Pink) {i}":  ScarletMaidenLocationData("Heartsanity", 30_028_0 + i, NPCRegions.OrcAxeThrowerPink) for i in range(1, 4)},
    **{f"Heartsanity: Snake Huntress {i}":          ScarletMaidenLocationData("Heartsanity", 30_029_0 + i, NPCRegions.SnakeHuntress) for i in range(1, 4)},
    **{f"Heartsanity: Imp Girl {i}":                ScarletMaidenLocationData("Heartsanity", 30_030_0 + i, NPCRegions.ImpGirl) for i in range(1, 4)},
    **{f"Heartsanity: Golden Slime {i}":            ScarletMaidenLocationData("Heartsanity", 30_031_0 + i, NPCRegions.GoldenSlime) for i in range(1, 4)},
    **{f"Heartsanity: Earth Mother {i}":            ScarletMaidenLocationData("Heartsanity - Boss", 30_062_0 + i, [RegionNames.MinesBoss]) for i in range(1, 4)},
    **{f"Heartsanity: The Grand Archivist {i}":     ScarletMaidenLocationData("Heartsanity - Boss", 30_063_0 + i, [RegionNames.LibraryBoss]) for i in range(1, 4)},
    **{f"Heartsanity: Queen Lily {i}":              ScarletMaidenLocationData("Heartsanity - Boss", 30_064_0 + i, [RegionNames.ForestBoss]) for i in range(1, 4)},
    **{f"Heartsanity: Cold Hearted Bitch {i}":      ScarletMaidenLocationData("Heartsanity - Boss", 30_065_0 + i, [RegionNames.FrozenBoss]) for i in range(1, 4)},

    # Questsanity
    **{f"Cogwheel {i}":                 ScarletMaidenLocationData("Questsanity - Items", 40_1_000 + i, [RegionNames.Mines, RegionNames.Library, RegionNames.Forest, RegionNames.Frozen, RegionNames.Sanctum]) for i in range(1, 51)},
    "Questsanity: Steamy Contraptions": ScarletMaidenLocation("Questsanity", 40_1_000),
    **{f"Golden Mask {i}":              ScarletMaidenLocationData("Questsanity - Items", 40_2_000 + i, [RegionNames.Mines, RegionNames.Library, RegionNames.Forest, RegionNames.Frozen, RegionNames.Sanctum]) for i in range(1, 51)},
    "Questsanity: Masquerade":          ScarletMaidenLocation("Questsanity", 40_2_000),
    **{f"Music Sheet {i}":              ScarletMaidenLocationData("Questsanity - Items", 40_3_000 + i, [RegionNames.Library, RegionNames.Forest, RegionNames.Frozen, RegionNames.Sanctum]) for i in range(1, 51)},
    "Questsanity: Magic Flute":         ScarletMaidenLocation("Questsanity", 40_3_000),
    **{f"Fertilizer {i}":               ScarletMaidenLocationData("Questsanity - Items", 40_4_000 + i, [RegionNames.Library, RegionNames.Forest, RegionNames.Frozen, RegionNames.Sanctum]) for i in range(1, 51)},
    "Questsanity: Green Delight":       ScarletMaidenLocation("Questsanity", 40_4_000),
    **{f"Leather Strap {i}":            ScarletMaidenLocationData("Questsanity - Items", 40_5_000 + i, [RegionNames.Library, RegionNames.Forest, RegionNames.Frozen, RegionNames.Sanctum]) for i in range(1, 51)},
    "Questsanity: It's a Strap!":       ScarletMaidenLocation("Questsanity", 40_5_000),
    **{f"Golden Nugget {i}":            ScarletMaidenLocationData("Questsanity - Items", 40_6_000 + i, [RegionNames.Library, RegionNames.Forest, RegionNames.Frozen, RegionNames.Sanctum]) for i in range(1, 51)},
    "Questsanity: Gold Digger":         ScarletMaidenLocation("Questsanity", 40_6_000),
    **{f"Void Crystal {i}":             ScarletMaidenLocationData("Questsanity - Items", 40_7_000 + i, [RegionNames.Library, RegionNames.Forest, RegionNames.Frozen, RegionNames.Sanctum]) for i in range(1, 51)},
    "Questsanity: Portal of Pleasure":  ScarletMaidenLocation("Questsanity", 40_7_000),
}