class RegionNames:
    Hub = "Hub"
    Mines = "Mines of Sorrow"
    MinesBoss = "Mines of Sorrow - Boss Room"
    Library = "The Royal Library"
    LibraryBoss = "The Royal Library - Boss Room"
    Forest = "Subterranean Forest"
    ForestBoss = "Subterranean Forest - Boss Room"
    Frozen = "Frozen Passage"
    FrozenBoss = "Frozen Passage - Boss Room"
    Sanctum = "Twisted Sanctum"
    SanctumBoss = "Twisted Sanctum - Boss Room"

class NPCRegions: # Vanilla spawn regions. Maybe make these shuffleable at some point.
    OrcWarrior = [RegionNames.Mines]
    GoblinShooter = [RegionNames.Mines]
    PlantGirl = [RegionNames.Mines]
    TriboobHuntress = [RegionNames.Mines, RegionNames.Forest]
    WickedWitch = [RegionNames.Mines]
    AquaSlime = [RegionNames.Mines]
    DarkElfAssassin = [RegionNames.Mines, RegionNames.Library]
    RubySlime = [RegionNames.Library]
    OrcAxeThrowerGreen = [RegionNames.Library]
    Succubus = [RegionNames.Library, RegionNames.Forest]
    Wolfina = [RegionNames.Library, RegionNames.Forest]
    Gimp = [RegionNames.Library]
    Fairie = [RegionNames.Library]
    TriboobCrusher = [RegionNames.Library, RegionNames.Sanctum] # Sanctum unmentioned in gallery
    DarkElfGoddess = [RegionNames.Library, RegionNames.Forest, RegionNames.Sanctum] # Sanctum unmentioned in gallery
    EmeraldSlime = [RegionNames.Forest]
    Ogress = [RegionNames.Forest, RegionNames.Sanctum]
    PoisonIvy = [RegionNames.Forest]
    CorruptedWitch = [RegionNames.Forest, RegionNames.Frozen]
    GoblinBomber = [RegionNames.Forest, RegionNames.Frozen]
    TriboobDragonslayer = [RegionNames.Forest]
    MamaSlime = [RegionNames.Frozen, RegionNames.Sanctum] # Sanctum unmentioned in gallery
    ShieldMaiden = [RegionNames.Frozen]
    SnakeGirl = [RegionNames.Frozen]
    DarkSuccubus = [RegionNames.Frozen]
    OrcishGimp = [RegionNames.Sanctum]
    Foxy = [RegionNames.Sanctum]
    OrcAxeThrowerPink = [RegionNames.Sanctum]
    SnakeHuntress = [RegionNames.Sanctum]
    ImpGirl = [RegionNames.Sanctum]
    GoldenSlime = [RegionNames.Sanctum]
    CountCockula = [RegionNames.Library, RegionNames.Forest]
    ElvenFountain = [RegionNames.Mines, RegionNames.Library]
    MysteriousDjinn = [RegionNames.Mines, RegionNames.Library, RegionNames.Forest]
    HornyOgre = [RegionNames.Mines, RegionNames.Library, RegionNames.Forest]
    UnderworldNurse = [RegionNames.Mines, RegionNames.Library]
    LactatingGoddess = [RegionNames.Library, RegionNames.Forest]
    ShyElf = [RegionNames.Mines, RegionNames.Library]
    LustyGiant = [RegionNames.Mines, RegionNames.Library, RegionNames.Forest]
    HandsomeAdventurer = [RegionNames.Mines, RegionNames.Library, RegionNames.Forest]
    HungryGnome = [RegionNames.Library, RegionNames.Forest]
    CreepyBush = [RegionNames.Forest]
    FrozenMaiden = [RegionNames.Frozen]
    FrostyTraveler = [RegionNames.Frozen]
    Mimic = [RegionNames.Sanctum]
    RigorMortis = [RegionNames.Sanctum]
    GoblinKing = [RegionNames.Forest, RegionNames.Frozen, RegionNames.Sanctum] # Sanctum unmentioned in gallery
    MonumentOfStrength = [RegionNames.Forest, RegionNames.Frozen]
    FriendlyWitch = [RegionNames.Forest, RegionNames.Frozen]
    StonedWizard = [RegionNames.Frozen, RegionNames.Sanctum]
    MagicDragon = [RegionNames.Sanctum]
    MuscleGoddess = [RegionNames.Sanctum]
    MedicineMan = [RegionNames.Mines, RegionNames.MinesBoss, RegionNames.Library, RegionNames.LibraryBoss, RegionNames.Forest, RegionNames.ForestBoss, RegionNames.Frozen, RegionNames.ForestBoss, RegionNames.Sanctum]
    MarvinsManaPump = [RegionNames.Mines, RegionNames.MinesBoss, RegionNames.Library, RegionNames.LibraryBoss, RegionNames.Forest, RegionNames.ForestBoss, RegionNames.Frozen, RegionNames.ForestBoss, RegionNames.Sanctum]
